### PR TITLE
Skip dig src start

### PR DESCRIPTION
**Pull request by pderouen**
There are a few rare scenarios when you don't want Origen to automatically insert the digsrc instrument start command. This PR provides a way to turn it off.

### CODE REVIEW

**Comment by ginty** [comment]
Looks good.
Could we add a quick note on this to the (currently still a placeholder) UFlex pattern guide? - https://github.com/Origen-SDK/origen_testers/blob/master/templates/origen_guides/pattern/ultraflex.md.erb

**Comment by pderouen** [comment]
Is there a way to compile/serve the template to make sure it's what I expect?

**Comment by pderouen** [comment]
I just pointed a local origen workspace's Gemfile to my local testers gem and built the origen web docs to view it.

Ok, I think this should do the trick.

**Comment by ginty** [comment]
> Is there a way to compile/serve the template to make sure it's what I expect?

Yeah, it should just be `origen web compile templates/origen_guides` from within this app.

Thanks for the doc addition!

**Comment by pderouen** [comment]
> 
> 
> > Is there a way to compile/serve the template to make sure it's what I expect?
> 
> Yeah, it should just be `origen web compile templates/origen_guides` from within this app.

LOL, should've been obvious to me! Thanks.

**Pull request merged**
