### PR TITLE
Add support for flow description for 93K

### PR DESCRIPTION
**Pull request by rlaj**
~~~ruby
Flow.create interface: 'MyInterface' do
  flow.flow_name = 'SETUP'
  flow.flow_description = 'Setup Variables and Guardbands'

  test :setup_test, cont: true

end
~~~

renders;

~~~
-----------------------------------------------------------------
test_flow

  {
    run(setup_test);

  }, open,"SETUP","Set Variables and Guardbands"

end
-----------------------------------------------------------------
~~~

### CODE REVIEW

**Comment by info-rchitect** [comment]
@rlaj i like it! LGTM

**Comment by info-rchitect** [comment]
@rlaj can the description be  part of the Flow.create hash options?

**Comment by ginty** [comment]
Along similar lines, I believe this also works and I was wondering if it should be integrated with this?

~~~ruby
# Comments about this flow
Flow.create interface: 'MyInterface' do

  OrigenTesters::Flow.flow_comments  # => ["Comments about this flow"]

end
~~~

**Comment by redxeth** [comment]
Should it be:

~~~ruby
Flow.create interface: 'MyInterface' do |my_flow|
  my_flow.flow_name = 'SETUP'
  my_flow.flow_description = 'Setup Variables and Guardbands'
  my_flow.flow_comments = 'Comments about this flow'

  test :setup_test, cont: true

end
~~~

**Pull request merged**
