### PR TITLE
Fixed an error where flags weren't handled properly in the vars files

### PR DESCRIPTION
**Pull request by arkohler**
* Updated flow.rb to build the flow_control_variables and runtime_control_variables arrays with the final strings to be output
* Removed the uppercasing from vars.tf.erb
* Updated approved output.  Several files changed, but mostly this was a result of variables changing position in the list, they moved back to where they were before PR #54.
The important output difference is in flow_control_vars.tf.  I've indicated them with <--- below.
```
declarations

@AT22_BEA7F3B_FAILED = 0;
@ECT1_3_BEA7F3B_FAILED = 0;
@ECT2_1_BEA7F3B_FAILED = 0;
@ECT2_2_BEA7F3B_FAILED = 0;
@GRP1_BEA7F3B_FAILED = 0;
@GT_GRP1_BEA7F3B_FAILED = 0;
@GT_GRP2_BEA7F3B_FAILED = 0;
@IFA1_BEA7F3B_FAILED = 0;
@IFA2_BEA7F3B_FAILED = 0;
@IFALL1_BEA7F3B_FAILED = 0;
@IFALLB1_BEA7F3B_FAILED = 0;
@IFALLP1_BEA7F3B_PASSED = 0;
@IFALLPB1_BEA7F3B_PASSED = 0;
@IFAP1_BEA7F3B_PASSED = 0;
@IFAP2_BEA7F3B_PASSED = 0;
@IFAPB1_BEA7F3B_PASSED = 0;
@IFAPB2_BEA7F3B_PASSED = 0;
@JOB = "";
@L1T3_BEA7F3B_FAILED = 0;
@L1T5_BEA7F3B_FAILED = 0;
@L2T3_BEA7F3B_FAILED = 0;
@MY_FLAG = 0;
@My_Mixed_Flag = 0;    <---
@NT2_BEA7F3B_FAILED = 0;
@NT2_BEA7F3B_PASSED = 0;
@OOF_PASSCODE1_BEA7F3B_FAILED = 0;
@OOF_PASSCODE2_BEA7F3B_FAILED = 0;
@T5_BEA7F3B_RAN = 0;
@T6_BEA7F3B_RAN = 0;
@T7_BEA7F3B_RAN = 0;
@T8_BEA7F3B_RAN = 0;

end
-----------------------------------------------------------------
flags

user CZ = 0;
user EN1 = 0;
user EN2 = 0;
user EXTRAS = 0;
user MCEn_extras = 0;    <---
user MCEn_test = 0;    <---
user NVM_MINIMUM_COLD = 0;
user NVM_MINIMUM_FT = 0;
user NVM_MINIMUM_HOT = 0;
user NVM_MINIMUM_ROOM = 0;
user QUICK = 0;
user WORD1 = 0;
user WORD2 = 0;
user WORD3 = 0;

end

```

### CODE REVIEW

**Comment by redxeth** [comment]
@arkohler let me manually add your changes to my mid-merge workspace -- then will approve PR update...

**Comment by arkohler** [comment]
I've tried to fast-track this update since the live code generates broken flags.  The test cases look clean as far as I can tell, but if you have an additional case that doesn't work, please let me know and I'll patch it up quickly.

**Comment by redxeth** [comment]
It's all good looks good now, thanks!!

**Comment by ginty** [comment]
Included in 0.13.0

**Pull request merged**
