### PR TITLE
changed label overlay behavior for J750 tester to local label

### PR DESCRIPTION
**Pull request by pderouen**
global label breaks backward compatibility of origen_jtag

### CODE REVIEW

**Comment by pderouen** [comment]
@priyavadan  @redxeth  can you take a look at these changes to tester.overlay for label overlay?  Originally, all labels were global.  Now all labels are local unless global is requested.  Is this your expectation for J750 and uflex?

**Comment by redxeth** [comment]
@pderouen why are we changing the default overlay behavior?  Can you give detail?

I think changing default behavior will break people's apps and should be avoided where possible.

**Comment by pderouen** [comment]
@redxeth, tester implemented overlay is a new thing.  Previously origen_jtag handled overlay implementation.  It defaulted to local labels.  This change to local is to un-break apps and to un-break origen_jtag's regression test suite.

**Comment by pderouen** [comment]
The corresponding origen_jtag PR, which is waiting for this PR:
https://github.com/Origen-SDK/origen_jtag/pull/5

**Comment by pderouen** [comment]
In general I believe a local label unless global is requested is the correct behavior.  This is consistent with what was done originally and with the behavior of tester.label.

**Comment by redxeth** [comment]
OK-- I see.  Not sure I agree with you there that local should be default-- it was my understanding to do overlays in VBT you had to use only global labels.   So I dont get why origen_jtag doesn't use them by default.  Seems the approveds in origen_jtag are the ones that need fixing.

**Comment by pderouen** [comment]
Hmm, @rlaj ?

**Comment by redxeth** [comment]
Ok per our offline convo-- then let me amend-- default label for **subroutines** should be global, which is mostly how I have used it.  The approved examples here are not subroutines, so I'm ok with the change (although the comments after should change too) assuming @rlaj is as well.

**Comment by redxeth** [comment]
That said I would say that subroutine overlay examples that use global should be added to prove that they haven't been affected.

**Comment by pderouen** [comment]
@redxeth I don't know how to get the link to the file and line number added as a hyper-link to my comment.  But, origen_testers, has a test for sub routine style overlay in pattern\tester_overlay.rb, lines 40-43.

The expected behavior of the testers plug-in is in approved/generic_overlay_capture.  You can see the LVM pattern being created will add an import statement for the subroutine and insert the call to it in the appropriate location.  Currently, the tester plug in doesn't generate the svm pattern... maybe at some point in the future it will.

**Comment by redxeth** [comment]
@pderouen click on the line number then click on ellipsis that pops up.

image

**Comment by pderouen** [comment]
@redxeth, thanks for the pointer.  I may have misunderstood the change request.  You want a test case using the global label option, is this correct?  I agree this should be added to the testers plug in.

**Comment by redxeth** [comment]
Yes -- thought that global used by everyone for all overlays initially.  But if not- and global only really required by subr AND there isn't a test case then one needs to be added.  

Also put in a warning of some sort as you are changing the default behavior that users may have come to depend on.  At least until some future official revision occurs. (say something in the warning that the default will change so change your app accordingly).

**Comment by pderouen** [comment]
@redxeth, I added tests for the global label style.

**Comment by pderouen** [comment]
@redxeth, if we're happy with the implementation and coverage can this be approved and merged?

**Comment by redxeth** [comment]
@pderouen, first silicon Monday and PC with IT now, but will try to take a look later today.

**Comment by pderouen** [comment]
Well?  @priyavadan @redxeth can this be approved as is, any updates needed?  Should I try to find a different reviewer?

**Comment by redxeth** [comment]
@pderouen on it... sorry been quite busy.  Doing a quick regression with a couple of patts with our main app.

**Comment by pderouen** [comment]
Thanks @redxeth.  I'll wait a little longer to see if @priyavadan wants to weigh in and then merge if no changes are requested from him.

**Pull request merged**
