### PR TITLE
Fixed the pin_setup freq_count to define after op_code extended and m…

### PR DESCRIPTION
**Pull request by ThaoHuynhFsl**
…ake sure op_code extened is true when use freq_count

### CODE REVIEW

**Comment by ThaoHuynhFsl** [comment]
Hi guys:  can you take a quick look  at the change, merge and release.  Need the release next week so we i can run release for our app.  Thanks

**Comment by priyavadan** [comment]
Hi @ThaoHuynhFsl looks like checks have failed, can you please fix?

**Comment by priyavadan** [comment]
@ThaoHuynhFsl looks like a lint error, so should be a quick fix. Coverage has decreased as well , so would be good to get that up... thanks!

**Comment by ginty** [comment]
Included in 0.7.9.
@ThaoHuynhFsl, add your @freescale.com email address to your github account in order for your contributions to be assigned to you

**Pull request merged**
