### PR TITLE
Extend existing PatternCompilers to include J750 and V93K Platforms

### PR DESCRIPTION
**Pull request by rlaj**
There's a lot of code to look at here, I added quite a bit of tests in the specs test, so that might be a good place to look to get a feel for the existing API.

-------------------------------
Paths to compiler tools are now picked up as Origen site configs
```text
# origen_site_config.yml
origen_testers:
  :v93k_linux_pattern_compiler: '/path/to/v93k/tool/set'
  :j750_windows_pattern_compiler: '/path/to/j750/compiler'

```
-------------------------------
Just as before, the instantiated pattern compilers belong to dut, not testers (e.g.  dut.pattern_compilers(:pat_comp_1)).  Seemed a little counter-intuitive (at least to me) in the beginning, but I think its correct architecture.

-------------------------------
UltraFLEX Compiler - Moved some code around to be shared with J750 compiler enablement, but functionally works the same as before.
```ruby
# inside of dut class
      @ultraflex_compiler_options = {
        path: "#{Origen.root}/spec/patterns/atp/functional",
        clean: true,
        location: :local,
        recursive: false,
        output_directory: "#{Origen.root}/spec/patterns/bin",
        opcode_mode: 'single',
        comments: false,
        verbose: true
      }
#

dut.add_pattern_compiler(:id1, :ultraflex, dut.ultraflex_compiler_options)

```
-------------------------------
J750 Pattern compiler works pretty much same as UltraFLEX, of course with J750-specific options and it's own, unique toolset path.
```ruby
# inside of dut class
      @j750_compiler_options = {
        path: "#{Origen.root}/spec/patterns/atp/j750",
        clean: true,
        location: :local,
        recursive: false,
        output_directory: "#{Origen.root}/spec/patterns/bin/j750",
        pinmap_workbook: "#{Origen.root}/spec/patterns/atp/bist/bist_pins.txt",
        opcode_mode: 'single',
        comments: false
      }
#

dut.add_pattern_compiler(:id2, :j750, dut.j750_compiler_options)
```
-------------------------------
V93K Supports:
  - On-the-fly generation of aiv configuration file based on pattern compiler options (can specify compiler instance, or use default).
  - Multiport burst enablement with pattern compiler options; both single port and multiple port cases are handled
  - Digital Capture Settings auto-inserted into aiv (pre-compile) based on 'digcap' pattern compiler options
  - Given exisiting aiv and workspace setup, can run stand-alone outside of pattern generation (e.g. during program generation/module builds)
```ruby

# inside of dut class
      @v93k_compiler_options = {
        config_dir: "#{Origen.root}/spec/patterns",
        pinconfig: "compiler_pins.cfg",
        tmf: "timing_map_file.tmf",
        multiport: {
          port_bursts: {
            p_1: 'pattern_burst_1',
            p_2: 'pat_burst_two'
          },
          port_in_focus: 'p_FOCUS',
          prefix: 'mpb'
        },
        digcap: {
          pins: :porta,
          vps: 1,
          nrf: 1,
        },
      }
#

dut.add_pattern_compiler(:id3, :v93k, dut.v93k_compiler_options)
```

### CODE REVIEW

**Comment by priyavadan** [comment]
@rlaj the J750/UF changes look good to me!

Could you please look at the Travis CI fails and run a lint check? Thanks!

**Comment by priyavadan** [comment]
@rlaj LGTM! great PR, thanks!

**Comment by ginty** [comment]
Woot woot, this is awesome @rlaj 

Sorry to be that guy, but....some documentation?

Might just be mainly what you have above, but also should capture the options added to `origen g` to enable this.

**Comment by rlaj** [comment]
Will open a PR (shortly) in Origen core for documentation updates.

**Pull request merged**
