### PR TITLE
SMT8

### PR DESCRIPTION
**Pull request by ginty**
Adds V93K SMT8 support with similar capabilities as the existing SMT7 driver.

This branch has been used in a production application for some months to generate both SMT7 and SMT8 test programs and as such I am very confident that the additions for SMT8 have not caused any regressions in SMT7 or any other platforms.

Unfortunately there are many files showing as a diff and it will not be easy to review this line-line, but here are some comments on the changes to help the review process:

* approved/<non-SMT8 tester> - Some additional test cases were added
* approved/v93k - These files were moved to a new sub-directory to allow differentiation between the V93K SMT7 and SMT8 builds
* approved/v93k_smt8 - New approved output for SMT8
* lbin/* - The development environment has been updated to newer version of Origen where these files should be checked in
* lib/origen_testers/*.rb - There are quite a few additions to top-level lib files like `lib/origen_testers/flow.rb. This was to add infrastructure to generate imported flows (and groups for SMT8) as standalone sub-flows/programs. This is all potentially re-usable if we were to add support for IG-XL sub-flows in future.
* program/* and pattern/* - Minor changes to add new test cases to exercise some specific features that were tricky for SMT8
* templates/origen_guides/* - Added doc updates for SMT8
* lib/origen_testers/smartest_based_tester/* - The bulk of the changes are in here. SMT8 shares a lot in common with SMT7 and the SMT8 support has been implemented as a combination of shared/common SMT infrastructure and SMT8-specific files. Again, confidence is very high that these changes have not caused regressions in the SMT7 builds.

### CODE REVIEW

**Comment by info-rchitect** [comment]
@ginty, et al Thanks for all of the work!  It will take a me a bit to go through this, not so much as a review but as a learning experience.  One question, is there a way to get a hash of all of the SMT8 test methods and the associated test method parameters?

**Comment by ginty** [comment]
Hi @info-rchitect, as far as I know there is no ADV-provided test method library for SMT8, nothing like the AC/DC TMLs from SMT7.
The API for defining your own test method signatures is the same as for SMT7 and in general the SMT8 generator is API-compatible with the SMT7 generator.
All the `if tester.smt8?` branches we have in our app are to handle differences in the test method libraries and you will probably find that if you convert your library to SMT8 then the args will be slightly different.

**Comment by info-rchitect** [comment]
@ginty how does Origen compare with the native V93K program generator?

**Comment by ginty** [comment]
@info-rchitect, the native V93K program generator?

**Comment by info-rchitect** [comment]
@ginty yes

**Comment by ginty** [comment]
I'm asking what you are referring to?

**Comment by info-rchitect** [comment]
@ginty Does this PR have any code that interacts with the Excel file format that the ADV PG uses?

**Comment by ginty** [comment]
I've never heard of the ADV PG until now, so no it does not interact with that at all.

**Comment by ginty** [comment]
Anyone want to stick their neck out and bless this?

Or phrased another way, assuming no one really has any experience of SMT8 yet, does anyone object to going ahead and merging it based on the passing test cases for the other platforms?

**Comment by info-rchitect** [comment]
@ginty I think it is as safe as we can make it for the time being.  I will be working on margining our origen_testers internal version with this and that process should work out the kinks.

**Pull request merged**
