### PR TITLE
Igxl defer

### PR DESCRIPTION
**Pull request by pderouen**
Allow defer limits to be used for nodes that have all limits entered as sub tests

### CODE REVIEW

**Comment by priyavadan** [comment]
@pderouen should we add an example use case in the igxl specs ?

**Comment by pderouen** [comment]
Not sure why the coverage dropped after ADDing tests. I would have thought it was the code added to the test interface. But, the report shows the coverage on that file went up.

**Review by priyavadan — APPROVED** [review]
looks good to me, did not understand either why coverage went down a bit.

**Comment by pderouen** [comment]
Thanks, I will merge this later today if there are no objections.

**Pull request merged**
